//
//  CoinsListPresenter.swift
//  cryptocurrency_manager
//
//  Created by Caua Mistura on 14/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CoinsListPresentationLogic {
    func presentGlobalValues(response: CoinsList.FetchGlobalValues.Response)
    func presentListCoins(response: CoinsList.FetchListCoin.Response)
    func presentError(error: CryptoCurrenciesError)
}

class CoinsListPresenter: CoinsListPresentationLogic {
    weak var viewController: CoinsListDisplayLogic?
    
    func presentGlobalValues(response: CoinsList.FetchGlobalValues.Response) {
        var globalValues: [CoinsList.FetchGlobalValues.ViewModel.GlobalValues] = []
        
        for (_, value) in response.totalMarketCap {
            globalValues.append(
                CoinsList.FetchGlobalValues.ViewModel.GlobalValues (title: "Capitalizacao de mercado global", value: value.toCurrency())
            )
        }
        
        for (_, value) in response.totalVolume {
            globalValues.append(
                CoinsList.FetchGlobalValues.ViewModel.GlobalValues (title: "Volume em 24 horas", value: value.toCurrency())
            )
        }
        
        let viewModel = CoinsList.FetchGlobalValues.ViewModel(globalValues: globalValues)
    }
    
    func presentListCoins(response: CoinsList.FetchListCoin.Response) {
        <#code#>
    }
    
    func presentError(error: CryptoCurrenciesError) {
        <#code#>
    }
}

extension Double {
    func toCurrency() -> String {
        let numberFormat = NumberFormatter()
        numberFormat.numberStyle = .currency
        numberFormat.locale = Locale(identifier: "pt_BR")
    }
}
