//
//  CoinsListModels.swift
//  cryptocurrency_manager
//
//  Created by Caua Mistura on 14/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CoinsList {

  enum FetchGlobalValues {
      struct Request {
          let baseCoin: String
      }
      struct Response {
          let baseCoin: String
          let totalMarketCap: [String: Double]
          let totalVolume: [String: Double]
      }
      struct ViewModel {
          struct GlobalValues {
              let title: String
              let value: String
          }
          let globalValues: [GlobalValues]
      }
  }
    
    enum FetchListCoin {
        struct Request {
            let baseCoin: String
            let orderBy: String
            let top: Int
            let pricePercentage: String
        }
        struct Response {
            let baseCoin: String
            let id,
                symbol,
                name: String
            let image: String
            let currentPrice,
                marketCap: Double
            let marketCapRank: Int?
            let marketCapChangePercentage: Double
        }
        struct ViewModel {
            struct Coin {
                let id: String
                let name: String
                let rank: String
                let iconURL: String
                let symbol: String
                let price: String
                let priceChangedPercentage: String
                let marketCapitalization: String
            }
            let coins: [Coin]
        }
    }
}
