//
//  CoinsListWorker.swift
//  cryptocurrency_manager
//
//  Created by Caua Mistura on 14/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CoinsListWorker {

    private let dataProvider: ListCoinDataProvider?
    private var completion: ((Result<[CoinModel]?, CryptoCurrenciesError>) -> Void)?
    
    init(dataProvider: ListCoinDataProvider = ListCoinDataProvider()) {
        self.dataProvider = dataProvider
        self.dataProvider?.delegate = self
    }
    
    func doFechListCoins(baseCoint: String, orderBy: String, top: Int, percentagePrice: String, completion: @escaping ((Result<[CoinModel]?, CryptoCurrenciesError>) -> Void)) {
        dataProvider?.fetchListCoins(by: baseCoint, with: nil, orderBy: orderBy, totalPerPage: top, page: 1, percentagePrice: percentagePrice)
        self.completion = completion
    }
}

extension CoinsListWorker: ListCoinDataProviderDelegate {
    func succes(model: Any) {
        guard let completion = completion else {
            fatalError("Completion not implemented!")
        }
        completion(.success(model as? [CoinModel]))
    }
    
    func errorData(_ provider: GenericDataProviderDelegate?, error: Error) {
        guard let completion = completion else {
            fatalError("Completion not implemented!")
        }
        if error.errorCode == 500 {
            completion(.failure(.internalServerError))
        } else if error.errorCode == 400 {
            completion(.failure(.badRequestError))
        } else if error.errorCode == 404 {
            completion(.failure(.notFoundError))
        } else {
            completion(.failure(.undefinedError))
        }
    }
}
