//
//  CoinsListModels.swift
//  cryptocurrency_manager
//
//  Created by Caua Mistura on 14/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CoinsList {

  enum Something {
      struct Request {
          
      }
      struct Response {
          
      }
      struct ViewModel {
          
      }
  }
}
